---
# tasks file for sap-preconfigure: configuration

# 05-configure-firewall.yml
- debug:
    msg: "SAP note 2772999 Step 5: Configure the Firewall"

- name: Stop and disable service firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Get status of firewalld
  command: bash -lc "systemctl status firewalld"
  register: command_result
  ignore_errors: True
- debug:
    var: command_result.stdout_lines, command_result.stderr_lines

...
