---
# tasks file for sap-preconfigure: configuration

# 04-linux-kernel-parameters.yml
- debug:
    msg: "SAP note 2002167 Step 4: Linux Kernel Parameters"

- name: Create file /etc/sysctl.d/sap.conf if it does not exist
  file:
    path: /etc/sysctl.d/sap.conf
    state: touch
    mode: 0644

- name: Set kernel parameter kernel.sem
  lineinfile:
    path: /etc/sysctl.d/sap.conf
    line: "kernel.sem=1250 256000 100 1024"
    state: present

- name: Set kernel parameter vm.max_map_count
  lineinfile:
    path: /etc/sysctl.d/sap.conf
    line: "vm.max_map_count = 2000000"
    state: present

...
